//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaaa
{
    
    
    public interface IService1
    {
        
        System.Threading.Tasks.Task<GetDataResponse> GetData(GetData request);
        
        System.Threading.Tasks.Task<GetDataUsingDataContractResponse> GetDataUsingDataContract(GetDataUsingDataContract request);
    }
    
    public partial class Service1Client : SoapServices.SoapClientBase, IService1
    {
        
        public virtual System.Threading.Tasks.Task<GetDataResponse> GetData(GetData request)
        {
            return this.CallAsync<GetData, GetDataResponse>("http://tempuri.org/IService1/GetData", request);
        }
        
        public virtual System.Threading.Tasks.Task<GetDataUsingDataContractResponse> GetDataUsingDataContract(GetDataUsingDataContract request)
        {
            return this.CallAsync<GetDataUsingDataContract, GetDataUsingDataContractResponse>("http://tempuri.org/IService1/GetDataUsingDataContract", request);
        }
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="GetData", Namespace="http://tempuri.org/")]
    public class GetData
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="value")]
        public int value;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="GetDataResponse", Namespace="http://tempuri.org/")]
    public class GetDataResponse
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="GetDataResult")]
        public string GetDataResult;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="GetDataUsingDataContract", Namespace="http://tempuri.org/")]
    public class GetDataUsingDataContract
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="composite")]
        public CompositeType composite;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public class CompositeType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="BoolValue")]
        public bool BoolValue;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="StringValue")]
        public string StringValue;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="GetDataUsingDataContractResponse", Namespace="http://tempuri.org/")]
    public class GetDataUsingDataContractResponse
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="GetDataUsingDataContractResult")]
        public CompositeType GetDataUsingDataContractResult;
    }
}
