//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaaa
{
    
    
    public interface OperationHistoryInterface
    {
        
        System.Threading.Tasks.Task<OperationHistoryData> GetOperationHistory(AuthorizationHeader request);
        
        System.Threading.Tasks.Task<OperationHistoryData> UpdateOperationData(AuthorizationHeader request);
        
        System.Threading.Tasks.Task<LanguageData> getLanguages(AuthorizationHeader request);
        
        System.Threading.Tasks.Task<PostalOrderEventsForMaiOutput> PostalOrderEventsForMail(PostalOrderEventsForMailInput request);
        
        System.Threading.Tasks.Task<SmsHistoryData> getSmsHistory(SmsHistoryRequest request);
    }
    
    public partial class OperationHistoryInterfaceClient : SoapServices.SoapClientBase, OperationHistoryInterface
    {
        
        public virtual System.Threading.Tasks.Task<OperationHistoryData> GetOperationHistory(AuthorizationHeader request)
        {
            return this.CallAsync<AuthorizationHeader, OperationHistoryData>(null, request);
        }
        
        public virtual System.Threading.Tasks.Task<OperationHistoryData> UpdateOperationData(AuthorizationHeader request)
        {
            return this.CallAsync<AuthorizationHeader, OperationHistoryData>(null, request);
        }
        
        public virtual System.Threading.Tasks.Task<LanguageData> getLanguages(AuthorizationHeader request)
        {
            return this.CallAsync<AuthorizationHeader, LanguageData>(null, request);
        }
        
        public virtual System.Threading.Tasks.Task<PostalOrderEventsForMaiOutput> PostalOrderEventsForMail(PostalOrderEventsForMailInput request)
        {
            return this.CallAsync<PostalOrderEventsForMailInput, PostalOrderEventsForMaiOutput>(null, request);
        }
        
        public virtual System.Threading.Tasks.Task<SmsHistoryData> getSmsHistory(SmsHistoryRequest request)
        {
            return this.CallAsync<SmsHistoryRequest, SmsHistoryData>(null, request);
        }
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="OperationHistoryRequest", Namespace="http://russianpost.org/operationhistory/data")]
    public class OperationHistoryRequest
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Barcode")]
        public string Barcode;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MessageType")]
        public int MessageType;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Language")]
        public string Language;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="AuthorizationHeader", Namespace="http://russianpost.org/operationhistory/data")]
    public class AuthorizationHeader
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.xmlsoap.org/soap/envelope/")]
        public bool mustUnderstand;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="login")]
        public string login;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="password")]
        public string password;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="OperationHistoryData", Namespace="http://russianpost.org/operationhistory/data")]
    public class OperationHistoryData
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="historyRecord")]
        public OperationHistoryRecord historyRecord;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="OperationHistoryRecord", Namespace="http://russianpost.org/operationhistory/data")]
    public class OperationHistoryRecord
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="AddressParameters")]
        public AddressParameters AddressParameters;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="FinanceParameters")]
        public FinanceParameters FinanceParameters;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ItemParameters")]
        public ItemParameters ItemParameters;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="OperationParameters")]
        public OperationParameters OperationParameters;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="UserParameters")]
        public UserParameters UserParameters;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="AddressParameters", Namespace="http://russianpost.org/operationhistory/data")]
    public class AddressParameters
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="DestinationAddress")]
        public Address DestinationAddress;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="OperationAddress")]
        public Address OperationAddress;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MailDirect")]
        public Country MailDirect;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="CountryFrom")]
        public Country CountryFrom;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="CountryOper")]
        public Country CountryOper;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="Address", Namespace="http://russianpost.org/operationhistory/data")]
    public class Address
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Index")]
        public string Index;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Description")]
        public string Description;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="Country", Namespace="http://russianpost.org/operationhistory/data")]
    public class Country
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Id")]
        public int Id;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Code2A")]
        public string Code2A;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Code3A")]
        public string Code3A;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Name")]
        public string Name;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="NameRU")]
        public string NameRU;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="NameEN")]
        public string NameEN;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="FinanceParameters", Namespace="http://russianpost.org/operationhistory/data")]
    public class FinanceParameters
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Payment")]
        public int Payment;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Value")]
        public int Value;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MassRate")]
        public int MassRate;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="InsrRate")]
        public int InsrRate;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="AirRate")]
        public int AirRate;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Rate")]
        public int Rate;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="ItemParameters", Namespace="http://russianpost.org/operationhistory/data")]
    public class ItemParameters
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Barcode")]
        public string Barcode;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Internum")]
        public string Internum;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ValidRuType")]
        public bool ValidRuType;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ValidEnType")]
        public bool ValidEnType;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ComplexItemName")]
        public string ComplexItemName;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MailRank")]
        public Rtm02Parameter MailRank;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="PostMark")]
        public Rtm02Parameter PostMark;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MailType")]
        public Rtm02Parameter MailType;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MailCtg")]
        public Rtm02Parameter MailCtg;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Mass")]
        public int Mass;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MaxMassRU")]
        public int MaxMassRU;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MaxMassEN")]
        public int MaxMassEN;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="Rtm02Parameter", Namespace="http://russianpost.org/operationhistory/data")]
    public class Rtm02Parameter
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Id")]
        public int Id;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Name")]
        public string Name;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="OperationParameters", Namespace="http://russianpost.org/operationhistory/data")]
    public class OperationParameters
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="OperType")]
        public Rtm02Parameter OperType;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="OperAttr")]
        public Rtm02Parameter OperAttr;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="OperDate")]
        public System.DateTime OperDate;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="UserParameters", Namespace="http://russianpost.org/operationhistory/data")]
    public class UserParameters
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SendCtg")]
        public Rtm02Parameter SendCtg;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Sndr")]
        public string Sndr;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Rcpn")]
        public string Rcpn;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="UpdateOperationRequest", Namespace="http://russianpost.org/operationhistory/data")]
    public class UpdateOperationRequest
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="RequestType")]
        public string RequestType;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SourceOperation")]
        public OperationHistoryRecord SourceOperation;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="TargetOperation")]
        public OperationHistoryRecord TargetOperation;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ReasonDescription")]
        public string ReasonDescription;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="InitiatorDepartment")]
        public int InitiatorDepartment;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ExecutorIP")]
        public string ExecutorIP;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="LanguageData", Namespace="http://russianpost.org/operationhistory/data")]
    public class LanguageData
    {
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="PostalOrderEventsForMailInput", Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public class PostalOrderEventsForMailInput
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Barcode;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="PostalOrderEventsForMaiOutput", Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public class PostalOrderEventsForMaiOutput
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="PostalOrderEvent")]
        public PostalOrderEvent PostalOrderEvent;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="PostalOrderEvent", Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public class PostalOrderEvent
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EventDateTime;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int EventType;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EventName;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IndexTo;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IndexEvent;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SumPaymentForward;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryEventCode;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryToCode;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="SmsHistoryRequest", Namespace="http://russianpost.org/sms-info/data")]
    public class SmsHistoryRequest
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Barcode")]
        public string Barcode;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Language")]
        public string Language;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="SmsHistoryData", Namespace="http://russianpost.org/sms-info/data")]
    public class SmsHistoryData
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="historyRecord")]
        public SmsHistoryRecord historyRecord;
    }
    
    [System.Xml.Serialization.XmlRootAttribute(ElementName="SmsHistoryRecord", Namespace="http://russianpost.org/sms-info/data")]
    public class SmsHistoryRecord
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Id")]
        public int Id;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Number")]
        public string Number;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="NotificationTypeID")]
        public int NotificationTypeID;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="NotificationTypeName")]
        public string NotificationTypeName;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="NotificationStatusID")]
        public int NotificationStatusID;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="NotificationStatusName")]
        public string NotificationStatusName;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="NotificationStatusDate")]
        public System.DateTime NotificationStatusDate;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SendedID")]
        public int SendedID;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SourceOperation")]
        public string SourceOperation;
    }
}
