//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNs2
{
    
    
    public interface OperationHistoryInterface
    {
        
        System.Threading.Tasks.Task<OperationHistoryData> GetOperationHistory(AuthorizationHeader request);
        
        System.Threading.Tasks.Task<OperationHistoryData> UpdateOperationData(AuthorizationHeader request);
        
        System.Threading.Tasks.Task<LanguageData> getLanguages(AuthorizationHeader request);
        
        System.Threading.Tasks.Task<PostalOrderEventsForMaiOutput> PostalOrderEventsForMail(PostalOrderEventsForMailInput request);
        
        System.Threading.Tasks.Task<SmsHistoryData> getSmsHistory(SmsHistoryRequest request);
    }
    
    public partial class OperationHistoryInterfaceClient : SoapServices.SoapClientBase, OperationHistoryInterface
    {
        
        public virtual System.Threading.Tasks.Task<OperationHistoryData> GetOperationHistory(AuthorizationHeader request)
        {
            return this.CallAsync<AuthorizationHeader, OperationHistoryData>(null, request);
        }
        
        public virtual System.Threading.Tasks.Task<OperationHistoryData> UpdateOperationData(AuthorizationHeader request)
        {
            return this.CallAsync<AuthorizationHeader, OperationHistoryData>(null, request);
        }
        
        public virtual System.Threading.Tasks.Task<LanguageData> getLanguages(AuthorizationHeader request)
        {
            return this.CallAsync<AuthorizationHeader, LanguageData>(null, request);
        }
        
        public virtual System.Threading.Tasks.Task<PostalOrderEventsForMaiOutput> PostalOrderEventsForMail(PostalOrderEventsForMailInput request)
        {
            return this.CallAsync<PostalOrderEventsForMailInput, PostalOrderEventsForMaiOutput>(null, request);
        }
        
        public virtual System.Threading.Tasks.Task<SmsHistoryData> getSmsHistory(SmsHistoryRequest request)
        {
            return this.CallAsync<SmsHistoryRequest, SmsHistoryData>(null, request);
        }
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class OperationHistoryRequest
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Barcode;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageType;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Language;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class AuthorizationHeader
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.xmlsoap.org/soap/envelope/")]
        public bool mustUnderstand;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class OperationHistoryData
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OperationHistoryRecord[] historyRecord;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class OperationHistoryRecord
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressParameters AddressParameters;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FinanceParameters FinanceParameters;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ItemParameters ItemParameters;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public OperationParameters OperationParameters;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public UserParameters UserParameters;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class AddressParameters
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Address DestinationAddress;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Address OperationAddress;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Country MailDirect;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Country CountryFrom;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Country CountryOper;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class Address
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Index;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class Country
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code2A;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Code3A;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NameRU;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NameEN;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class FinanceParameters
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Payment;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Value;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MassRate;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int InsrRate;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int AirRate;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Rate;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class ItemParameters
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Barcode;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Internum;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ValidRuType;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ValidEnType;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ComplexItemName;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Rtm02Parameter MailRank;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Rtm02Parameter PostMark;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Rtm02Parameter MailType;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Rtm02Parameter MailCtg;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Mass;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int MaxMassRU;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int MaxMassEN;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class Rtm02Parameter
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class OperationParameters
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Rtm02Parameter OperType;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Rtm02Parameter OperAttr;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime OperDate;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class UserParameters
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Rtm02Parameter SendCtg;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sndr;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Rcpn;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class UpdateOperationRequest
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestType;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OperationHistoryRecord SourceOperation;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public OperationHistoryRecord TargetOperation;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReasonDescription;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int InitiatorDepartment;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ExecutorIP;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public class LanguageData
    {
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public class PostalOrderEventsForMailInput
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Barcode;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public class PostalOrderEventsForMaiOutput
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PostalOrderEvent[] PostalOrderEvent;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public class PostalOrderEvent
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EventDateTime;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int EventType;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EventName;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IndexTo;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IndexEvent;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SumPaymentForward;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryEventCode;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryToCode;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/sms-info/data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://russianpost.org/sms-info/data")]
    public class SmsHistoryRequest
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Barcode;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Language;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/sms-info/data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://russianpost.org/sms-info/data")]
    public class SmsHistoryData
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SmsHistoryRecord[] historyRecord;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/sms-info/data")]
    public class SmsHistoryRecord
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NotificationTypeID;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NotificationTypeName;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int NotificationStatusID;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NotificationStatusName;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime NotificationStatusDate;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int SendedID;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SourceOperation;
    }
}
