//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.ServiceReference3 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public partial class PostalOrderEventsForMailError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PostalOrderEventsForMailErrors errorIDField;
        
        private bool errorIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PostalOrderEventsForMailErrors ErrorID {
            get {
                return this.errorIDField;
            }
            set {
                this.errorIDField = value;
                this.RaisePropertyChanged("ErrorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorIDSpecified {
            get {
                return this.errorIDFieldSpecified;
            }
            set {
                this.errorIDFieldSpecified = value;
                this.RaisePropertyChanged("ErrorIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public enum PostalOrderEventsForMailErrors {
        
        /// <remarks/>
        InvalidLoginOrPassword,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public partial class PostalOrderEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberField;
        
        private System.DateTime eventDateTimeField;
        
        private bool eventDateTimeFieldSpecified;
        
        private string eventTypeField;
        
        private string eventNameField;
        
        private string indexToField;
        
        private string indexEventField;
        
        private string sumPaymentForwardField;
        
        private string countryEventCodeField;
        
        private string countryToCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EventDateTime {
            get {
                return this.eventDateTimeField;
            }
            set {
                this.eventDateTimeField = value;
                this.RaisePropertyChanged("EventDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventDateTimeSpecified {
            get {
                return this.eventDateTimeFieldSpecified;
            }
            set {
                this.eventDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("EventDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
                this.RaisePropertyChanged("EventType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
                this.RaisePropertyChanged("EventName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string IndexTo {
            get {
                return this.indexToField;
            }
            set {
                this.indexToField = value;
                this.RaisePropertyChanged("IndexTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string IndexEvent {
            get {
                return this.indexEventField;
            }
            set {
                this.indexEventField = value;
                this.RaisePropertyChanged("IndexEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string SumPaymentForward {
            get {
                return this.sumPaymentForwardField;
            }
            set {
                this.sumPaymentForwardField = value;
                this.RaisePropertyChanged("SumPaymentForward");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryEventCode {
            get {
                return this.countryEventCodeField;
            }
            set {
                this.countryEventCodeField = value;
                this.RaisePropertyChanged("CountryEventCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryToCode {
            get {
                return this.countryToCodeField;
            }
            set {
                this.countryToCodeField = value;
                this.RaisePropertyChanged("CountryToCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public partial class PostalOrderEventsForMailInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private string languageField;
        
        public PostalOrderEventsForMailInput() {
            this.languageField = "RUS";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("Barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("RUS")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class UpdateOperationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestType requestTypeField;
        
        private OperationHistoryRecord sourceOperationField;
        
        private OperationHistoryRecord targetOperationField;
        
        private string reasonDescriptionField;
        
        private string initiatorDepartmentField;
        
        private string executorIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestType RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("RequestType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OperationHistoryRecord SourceOperation {
            get {
                return this.sourceOperationField;
            }
            set {
                this.sourceOperationField = value;
                this.RaisePropertyChanged("SourceOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public OperationHistoryRecord TargetOperation {
            get {
                return this.targetOperationField;
            }
            set {
                this.targetOperationField = value;
                this.RaisePropertyChanged("TargetOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReasonDescription {
            get {
                return this.reasonDescriptionField;
            }
            set {
                this.reasonDescriptionField = value;
                this.RaisePropertyChanged("ReasonDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string InitiatorDepartment {
            get {
                return this.initiatorDepartmentField;
            }
            set {
                this.initiatorDepartmentField = value;
                this.RaisePropertyChanged("InitiatorDepartment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ExecutorIP {
            get {
                return this.executorIPField;
            }
            set {
                this.executorIPField = value;
                this.RaisePropertyChanged("ExecutorIP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public enum RequestType {
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class OperationHistoryRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddressParameters addressParametersField;
        
        private FinanceParameters financeParametersField;
        
        private ItemParameters itemParametersField;
        
        private OperationParameters operationParametersField;
        
        private UserParameters userParametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressParameters AddressParameters {
            get {
                return this.addressParametersField;
            }
            set {
                this.addressParametersField = value;
                this.RaisePropertyChanged("AddressParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FinanceParameters FinanceParameters {
            get {
                return this.financeParametersField;
            }
            set {
                this.financeParametersField = value;
                this.RaisePropertyChanged("FinanceParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ItemParameters ItemParameters {
            get {
                return this.itemParametersField;
            }
            set {
                this.itemParametersField = value;
                this.RaisePropertyChanged("ItemParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public OperationParameters OperationParameters {
            get {
                return this.operationParametersField;
            }
            set {
                this.operationParametersField = value;
                this.RaisePropertyChanged("OperationParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public UserParameters UserParameters {
            get {
                return this.userParametersField;
            }
            set {
                this.userParametersField = value;
                this.RaisePropertyChanged("UserParameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class AddressParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Address destinationAddressField;
        
        private Address operationAddressField;
        
        private Country mailDirectField;
        
        private Country countryFromField;
        
        private Country countryOperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Address DestinationAddress {
            get {
                return this.destinationAddressField;
            }
            set {
                this.destinationAddressField = value;
                this.RaisePropertyChanged("DestinationAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Address OperationAddress {
            get {
                return this.operationAddressField;
            }
            set {
                this.operationAddressField = value;
                this.RaisePropertyChanged("OperationAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Country MailDirect {
            get {
                return this.mailDirectField;
            }
            set {
                this.mailDirectField = value;
                this.RaisePropertyChanged("MailDirect");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Country CountryFrom {
            get {
                return this.countryFromField;
            }
            set {
                this.countryFromField = value;
                this.RaisePropertyChanged("CountryFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Country CountryOper {
            get {
                return this.countryOperField;
            }
            set {
                this.countryOperField = value;
                this.RaisePropertyChanged("CountryOper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string indexField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
                this.RaisePropertyChanged("Index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class Country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string code2AField;
        
        private string code3AField;
        
        private string nameField;
        
        private string nameRUField;
        
        private string nameENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code2A {
            get {
                return this.code2AField;
            }
            set {
                this.code2AField = value;
                this.RaisePropertyChanged("Code2A");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Code3A {
            get {
                return this.code3AField;
            }
            set {
                this.code3AField = value;
                this.RaisePropertyChanged("Code3A");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NameRU {
            get {
                return this.nameRUField;
            }
            set {
                this.nameRUField = value;
                this.RaisePropertyChanged("NameRU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NameEN {
            get {
                return this.nameENField;
            }
            set {
                this.nameENField = value;
                this.RaisePropertyChanged("NameEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class FinanceParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paymentField;
        
        private string valueField;
        
        private string massRateField;
        
        private string insrRateField;
        
        private string airRateField;
        
        private string rateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
                this.RaisePropertyChanged("Payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string MassRate {
            get {
                return this.massRateField;
            }
            set {
                this.massRateField = value;
                this.RaisePropertyChanged("MassRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string InsrRate {
            get {
                return this.insrRateField;
            }
            set {
                this.insrRateField = value;
                this.RaisePropertyChanged("InsrRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string AirRate {
            get {
                return this.airRateField;
            }
            set {
                this.airRateField = value;
                this.RaisePropertyChanged("AirRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("Rate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class ItemParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private string internumField;
        
        private bool validRuTypeField;
        
        private bool validEnTypeField;
        
        private string complexItemNameField;
        
        private Rtm02Parameter mailRankField;
        
        private Rtm02Parameter postMarkField;
        
        private Rtm02Parameter mailTypeField;
        
        private Rtm02Parameter mailCtgField;
        
        private string massField;
        
        private string maxMassRUField;
        
        private string maxMassENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("Barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Internum {
            get {
                return this.internumField;
            }
            set {
                this.internumField = value;
                this.RaisePropertyChanged("Internum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ValidRuType {
            get {
                return this.validRuTypeField;
            }
            set {
                this.validRuTypeField = value;
                this.RaisePropertyChanged("ValidRuType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ValidEnType {
            get {
                return this.validEnTypeField;
            }
            set {
                this.validEnTypeField = value;
                this.RaisePropertyChanged("ValidEnType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ComplexItemName {
            get {
                return this.complexItemNameField;
            }
            set {
                this.complexItemNameField = value;
                this.RaisePropertyChanged("ComplexItemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Rtm02Parameter MailRank {
            get {
                return this.mailRankField;
            }
            set {
                this.mailRankField = value;
                this.RaisePropertyChanged("MailRank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Rtm02Parameter PostMark {
            get {
                return this.postMarkField;
            }
            set {
                this.postMarkField = value;
                this.RaisePropertyChanged("PostMark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Rtm02Parameter MailType {
            get {
                return this.mailTypeField;
            }
            set {
                this.mailTypeField = value;
                this.RaisePropertyChanged("MailType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Rtm02Parameter MailCtg {
            get {
                return this.mailCtgField;
            }
            set {
                this.mailCtgField = value;
                this.RaisePropertyChanged("MailCtg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=9)]
        public string Mass {
            get {
                return this.massField;
            }
            set {
                this.massField = value;
                this.RaisePropertyChanged("Mass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=10)]
        public string MaxMassRU {
            get {
                return this.maxMassRUField;
            }
            set {
                this.maxMassRUField = value;
                this.RaisePropertyChanged("MaxMassRU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=11)]
        public string MaxMassEN {
            get {
                return this.maxMassENField;
            }
            set {
                this.maxMassENField = value;
                this.RaisePropertyChanged("MaxMassEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class Rtm02Parameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class OperationParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Rtm02Parameter operTypeField;
        
        private Rtm02Parameter operAttrField;
        
        private System.DateTime operDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Rtm02Parameter OperType {
            get {
                return this.operTypeField;
            }
            set {
                this.operTypeField = value;
                this.RaisePropertyChanged("OperType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Rtm02Parameter OperAttr {
            get {
                return this.operAttrField;
            }
            set {
                this.operAttrField = value;
                this.RaisePropertyChanged("OperAttr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime OperDate {
            get {
                return this.operDateField;
            }
            set {
                this.operDateField = value;
                this.RaisePropertyChanged("OperDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class UserParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Rtm02Parameter sendCtgField;
        
        private string sndrField;
        
        private string rcpnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Rtm02Parameter SendCtg {
            get {
                return this.sendCtgField;
            }
            set {
                this.sendCtgField = value;
                this.RaisePropertyChanged("SendCtg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sndr {
            get {
                return this.sndrField;
            }
            set {
                this.sndrField = value;
                this.RaisePropertyChanged("Sndr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Rcpn {
            get {
                return this.rcpnField;
            }
            set {
                this.rcpnField = value;
                this.RaisePropertyChanged("Rcpn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://russianpost.org/operationhistory", ConfigurationName="ServiceReference3.OperationHistoryInterface")]
    public interface OperationHistoryInterface {
        
        // CODEGEN: Generating message contract since the operation GetOperationHistory is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="AuthorizationFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="OperationHistoryFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="LanguageFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientApp.ServiceReference3.GetOperationHistoryResponse GetOperationHistory(ClientApp.ServiceReference3.GetOperationHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference3.GetOperationHistoryResponse> GetOperationHistoryAsync(ClientApp.ServiceReference3.GetOperationHistoryRequest request);
        
        // CODEGEN: Generating message contract since the operation UpdateOperationData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="AuthorizationFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="OperationHistoryFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="LanguageFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientApp.ServiceReference3.UpdateOperationDataResponse UpdateOperationData(ClientApp.ServiceReference3.UpdateOperationDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference3.UpdateOperationDataResponse> UpdateOperationDataAsync(ClientApp.ServiceReference3.UpdateOperationDataRequest request);
        
        // CODEGEN: Generating message contract since the operation getLanguages is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="AuthorizationFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="OperationHistoryFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="LanguageFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientApp.ServiceReference3.getLanguageResponse getLanguages(ClientApp.ServiceReference3.getLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference3.getLanguageResponse> getLanguagesAsync(ClientApp.ServiceReference3.getLanguageRequest request);
        
        // CODEGEN: Generating message contract since the operation PostalOrderEventsForMail is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApp.ServiceReference3.PostalOrderEventsForMailError[]), Action="", Name="PostalOrderEventsForMailFault", Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientApp.ServiceReference3.Response PostalOrderEventsForMail(ClientApp.ServiceReference3.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference3.Response> PostalOrderEventsForMailAsync(ClientApp.ServiceReference3.Request request);
        
        // CODEGEN: Generating message contract since the operation getSmsHistory is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="SmsHistoryFaultReason", Namespace="http://russianpost.org/sms-info/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="LanguageFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="AuthorizationFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientApp.ServiceReference3.getSmsHistoryResponse getSmsHistory(ClientApp.ServiceReference3.getSmsHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApp.ServiceReference3.getSmsHistoryResponse> getSmsHistoryAsync(ClientApp.ServiceReference3.getSmsHistoryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/operationhistory/data")]
    public partial class AuthorizationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        private bool mustUnderstandField;
        
        public AuthorizationHeader() {
            this.mustUnderstandField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.xmlsoap.org/soap/envelope/")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool mustUnderstand {
            get {
                return this.mustUnderstandField;
            }
            set {
                this.mustUnderstandField = value;
                this.RaisePropertyChanged("mustUnderstand");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/operationhistory/data")]
    public partial class OperationHistoryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private int messageTypeField;
        
        private string languageField;
        
        public OperationHistoryRequest() {
            this.languageField = "RUS";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("Barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute("RUS")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOperationHistoryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        public ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        public ClientApp.ServiceReference3.OperationHistoryRequest OperationHistoryRequest;
        
        public GetOperationHistoryRequest() {
        }
        
        public GetOperationHistoryRequest(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.OperationHistoryRequest OperationHistoryRequest) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.OperationHistoryRequest = OperationHistoryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOperationHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("historyRecord", IsNullable=false)]
        public ClientApp.ServiceReference3.OperationHistoryRecord[] OperationHistoryData;
        
        public GetOperationHistoryResponse() {
        }
        
        public GetOperationHistoryResponse(ClientApp.ServiceReference3.OperationHistoryRecord[] OperationHistoryData) {
            this.OperationHistoryData = OperationHistoryData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOperationDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        public ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        public ClientApp.ServiceReference3.UpdateOperationRequest UpdateOperationRequest;
        
        public UpdateOperationDataRequest() {
        }
        
        public UpdateOperationDataRequest(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.UpdateOperationRequest UpdateOperationRequest) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.UpdateOperationRequest = UpdateOperationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOperationDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("historyRecord", IsNullable=false)]
        public ClientApp.ServiceReference3.OperationHistoryRecord[] OperationHistoryData;
        
        public UpdateOperationDataResponse() {
        }
        
        public UpdateOperationDataResponse(ClientApp.ServiceReference3.OperationHistoryRecord[] OperationHistoryData) {
            this.OperationHistoryData = OperationHistoryData;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/operationhistory/data")]
    public partial class LanguageDataLanguage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLanguageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        public ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader;
        
        public getLanguageRequest() {
        }
        
        public getLanguageRequest(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader) {
            this.AuthorizationHeader = AuthorizationHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Language", IsNullable=false)]
        public ClientApp.ServiceReference3.LanguageDataLanguage[] LanguageData;
        
        public getLanguageResponse() {
        }
        
        public getLanguageResponse(ClientApp.ServiceReference3.LanguageDataLanguage[] LanguageData) {
            this.LanguageData = LanguageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        public ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data", Order=0)]
        public ClientApp.ServiceReference3.PostalOrderEventsForMailInput PostalOrderEventsForMailInput;
        
        public Request() {
        }
        
        public Request(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.PostalOrderEventsForMailInput PostalOrderEventsForMailInput) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.PostalOrderEventsForMailInput = PostalOrderEventsForMailInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ClientApp.ServiceReference3.PostalOrderEvent[] PostalOrderEventsForMaiOutput;
        
        public Response() {
        }
        
        public Response(ClientApp.ServiceReference3.PostalOrderEvent[] PostalOrderEventsForMaiOutput) {
            this.PostalOrderEventsForMaiOutput = PostalOrderEventsForMaiOutput;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/sms-info/data")]
    public partial class SmsHistoryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private string languageField;
        
        public SmsHistoryRequest() {
            this.languageField = "RUS";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("Barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute("RUS")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/sms-info/data")]
    public partial class SmsHistoryRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string numberField;
        
        private string notificationTypeIDField;
        
        private string notificationTypeNameField;
        
        private string notificationStatusIDField;
        
        private string notificationStatusNameField;
        
        private System.DateTime notificationStatusDateField;
        
        private string sendedIDField;
        
        private string sourceOperationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string NotificationTypeID {
            get {
                return this.notificationTypeIDField;
            }
            set {
                this.notificationTypeIDField = value;
                this.RaisePropertyChanged("NotificationTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NotificationTypeName {
            get {
                return this.notificationTypeNameField;
            }
            set {
                this.notificationTypeNameField = value;
                this.RaisePropertyChanged("NotificationTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string NotificationStatusID {
            get {
                return this.notificationStatusIDField;
            }
            set {
                this.notificationStatusIDField = value;
                this.RaisePropertyChanged("NotificationStatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NotificationStatusName {
            get {
                return this.notificationStatusNameField;
            }
            set {
                this.notificationStatusNameField = value;
                this.RaisePropertyChanged("NotificationStatusName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime NotificationStatusDate {
            get {
                return this.notificationStatusDateField;
            }
            set {
                this.notificationStatusDateField = value;
                this.RaisePropertyChanged("NotificationStatusDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string SendedID {
            get {
                return this.sendedIDField;
            }
            set {
                this.sendedIDField = value;
                this.RaisePropertyChanged("SendedID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SourceOperation {
            get {
                return this.sourceOperationField;
            }
            set {
                this.sourceOperationField = value;
                this.RaisePropertyChanged("SourceOperation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSmsHistoryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        public ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/sms-info/data", Order=0)]
        public ClientApp.ServiceReference3.SmsHistoryRequest SmsHistoryRequest;
        
        public getSmsHistoryRequest() {
        }
        
        public getSmsHistoryRequest(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.SmsHistoryRequest SmsHistoryRequest) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.SmsHistoryRequest = SmsHistoryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSmsHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/sms-info/data", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("historyRecord", IsNullable=false)]
        public ClientApp.ServiceReference3.SmsHistoryRecord[] SmsHistoryData;
        
        public getSmsHistoryResponse() {
        }
        
        public getSmsHistoryResponse(ClientApp.ServiceReference3.SmsHistoryRecord[] SmsHistoryData) {
            this.SmsHistoryData = SmsHistoryData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperationHistoryInterfaceChannel : ClientApp.ServiceReference3.OperationHistoryInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationHistoryInterfaceClient : System.ServiceModel.ClientBase<ClientApp.ServiceReference3.OperationHistoryInterface>, ClientApp.ServiceReference3.OperationHistoryInterface {
        
        public OperationHistoryInterfaceClient() {
        }
        
        public OperationHistoryInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationHistoryInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationHistoryInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationHistoryInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.ServiceReference3.GetOperationHistoryResponse ClientApp.ServiceReference3.OperationHistoryInterface.GetOperationHistory(ClientApp.ServiceReference3.GetOperationHistoryRequest request) {
            return base.Channel.GetOperationHistory(request);
        }
        
        public ClientApp.ServiceReference3.OperationHistoryRecord[] GetOperationHistory(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.OperationHistoryRequest OperationHistoryRequest) {
            ClientApp.ServiceReference3.GetOperationHistoryRequest inValue = new ClientApp.ServiceReference3.GetOperationHistoryRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.OperationHistoryRequest = OperationHistoryRequest;
            ClientApp.ServiceReference3.GetOperationHistoryResponse retVal = ((ClientApp.ServiceReference3.OperationHistoryInterface)(this)).GetOperationHistory(inValue);
            return retVal.OperationHistoryData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApp.ServiceReference3.GetOperationHistoryResponse> ClientApp.ServiceReference3.OperationHistoryInterface.GetOperationHistoryAsync(ClientApp.ServiceReference3.GetOperationHistoryRequest request) {
            return base.Channel.GetOperationHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference3.GetOperationHistoryResponse> GetOperationHistoryAsync(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.OperationHistoryRequest OperationHistoryRequest) {
            ClientApp.ServiceReference3.GetOperationHistoryRequest inValue = new ClientApp.ServiceReference3.GetOperationHistoryRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.OperationHistoryRequest = OperationHistoryRequest;
            return ((ClientApp.ServiceReference3.OperationHistoryInterface)(this)).GetOperationHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.ServiceReference3.UpdateOperationDataResponse ClientApp.ServiceReference3.OperationHistoryInterface.UpdateOperationData(ClientApp.ServiceReference3.UpdateOperationDataRequest request) {
            return base.Channel.UpdateOperationData(request);
        }
        
        public ClientApp.ServiceReference3.OperationHistoryRecord[] UpdateOperationData(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.UpdateOperationRequest UpdateOperationRequest) {
            ClientApp.ServiceReference3.UpdateOperationDataRequest inValue = new ClientApp.ServiceReference3.UpdateOperationDataRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.UpdateOperationRequest = UpdateOperationRequest;
            ClientApp.ServiceReference3.UpdateOperationDataResponse retVal = ((ClientApp.ServiceReference3.OperationHistoryInterface)(this)).UpdateOperationData(inValue);
            return retVal.OperationHistoryData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApp.ServiceReference3.UpdateOperationDataResponse> ClientApp.ServiceReference3.OperationHistoryInterface.UpdateOperationDataAsync(ClientApp.ServiceReference3.UpdateOperationDataRequest request) {
            return base.Channel.UpdateOperationDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference3.UpdateOperationDataResponse> UpdateOperationDataAsync(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.UpdateOperationRequest UpdateOperationRequest) {
            ClientApp.ServiceReference3.UpdateOperationDataRequest inValue = new ClientApp.ServiceReference3.UpdateOperationDataRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.UpdateOperationRequest = UpdateOperationRequest;
            return ((ClientApp.ServiceReference3.OperationHistoryInterface)(this)).UpdateOperationDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.ServiceReference3.getLanguageResponse ClientApp.ServiceReference3.OperationHistoryInterface.getLanguages(ClientApp.ServiceReference3.getLanguageRequest request) {
            return base.Channel.getLanguages(request);
        }
        
        public ClientApp.ServiceReference3.LanguageDataLanguage[] getLanguages(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader) {
            ClientApp.ServiceReference3.getLanguageRequest inValue = new ClientApp.ServiceReference3.getLanguageRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            ClientApp.ServiceReference3.getLanguageResponse retVal = ((ClientApp.ServiceReference3.OperationHistoryInterface)(this)).getLanguages(inValue);
            return retVal.LanguageData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApp.ServiceReference3.getLanguageResponse> ClientApp.ServiceReference3.OperationHistoryInterface.getLanguagesAsync(ClientApp.ServiceReference3.getLanguageRequest request) {
            return base.Channel.getLanguagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference3.getLanguageResponse> getLanguagesAsync(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader) {
            ClientApp.ServiceReference3.getLanguageRequest inValue = new ClientApp.ServiceReference3.getLanguageRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            return ((ClientApp.ServiceReference3.OperationHistoryInterface)(this)).getLanguagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.ServiceReference3.Response ClientApp.ServiceReference3.OperationHistoryInterface.PostalOrderEventsForMail(ClientApp.ServiceReference3.Request request) {
            return base.Channel.PostalOrderEventsForMail(request);
        }
        
        public ClientApp.ServiceReference3.PostalOrderEvent[] PostalOrderEventsForMail(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.PostalOrderEventsForMailInput PostalOrderEventsForMailInput) {
            ClientApp.ServiceReference3.Request inValue = new ClientApp.ServiceReference3.Request();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.PostalOrderEventsForMailInput = PostalOrderEventsForMailInput;
            ClientApp.ServiceReference3.Response retVal = ((ClientApp.ServiceReference3.OperationHistoryInterface)(this)).PostalOrderEventsForMail(inValue);
            return retVal.PostalOrderEventsForMaiOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApp.ServiceReference3.Response> ClientApp.ServiceReference3.OperationHistoryInterface.PostalOrderEventsForMailAsync(ClientApp.ServiceReference3.Request request) {
            return base.Channel.PostalOrderEventsForMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference3.Response> PostalOrderEventsForMailAsync(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.PostalOrderEventsForMailInput PostalOrderEventsForMailInput) {
            ClientApp.ServiceReference3.Request inValue = new ClientApp.ServiceReference3.Request();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.PostalOrderEventsForMailInput = PostalOrderEventsForMailInput;
            return ((ClientApp.ServiceReference3.OperationHistoryInterface)(this)).PostalOrderEventsForMailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.ServiceReference3.getSmsHistoryResponse ClientApp.ServiceReference3.OperationHistoryInterface.getSmsHistory(ClientApp.ServiceReference3.getSmsHistoryRequest request) {
            return base.Channel.getSmsHistory(request);
        }
        
        public ClientApp.ServiceReference3.SmsHistoryRecord[] getSmsHistory(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.SmsHistoryRequest SmsHistoryRequest) {
            ClientApp.ServiceReference3.getSmsHistoryRequest inValue = new ClientApp.ServiceReference3.getSmsHistoryRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.SmsHistoryRequest = SmsHistoryRequest;
            ClientApp.ServiceReference3.getSmsHistoryResponse retVal = ((ClientApp.ServiceReference3.OperationHistoryInterface)(this)).getSmsHistory(inValue);
            return retVal.SmsHistoryData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApp.ServiceReference3.getSmsHistoryResponse> ClientApp.ServiceReference3.OperationHistoryInterface.getSmsHistoryAsync(ClientApp.ServiceReference3.getSmsHistoryRequest request) {
            return base.Channel.getSmsHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApp.ServiceReference3.getSmsHistoryResponse> getSmsHistoryAsync(ClientApp.ServiceReference3.AuthorizationHeader AuthorizationHeader, ClientApp.ServiceReference3.SmsHistoryRequest SmsHistoryRequest) {
            ClientApp.ServiceReference3.getSmsHistoryRequest inValue = new ClientApp.ServiceReference3.getSmsHistoryRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.SmsHistoryRequest = SmsHistoryRequest;
            return ((ClientApp.ServiceReference3.OperationHistoryInterface)(this)).getSmsHistoryAsync(inValue);
        }
    }
}
